# Gradle JVM Memory Allocation
org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=1024m -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError

# AndroidX Support
android.useAndroidX=true
android.enableJetifier=true

# Built-in Kotlin Enforcement (AGP 9+)
android.builtInKotlin=true
kotlin.incremental=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
